<?php

/**
 * @file
 * Main module file.
 */

/**
 * Adds an option to the overview field.
 *
 * @param array $options
 *   Contains all the options for the overview field.
 */
function dropsolid_product_basic_overview_field_options_alter(array &$options) {
  $options['product_overview'] = t('Show a list of product articles on your website');
  $options['product_overview_front'] = t('Show the last three promoted product articles');
  $options['block_winners_2019'] = t('Show list of 2019 winners');
  $options['block_winners_2020'] = t('Show list of 2020 winners');
}

/**
 * Defines what should be returned in the overview.
 *
 * @param string $key
 *   The key defined in hook_overview_options_alter().
 * @param array $output
 *   A renderable array of data, that needs to be displayed in the field.
 */
function dropsolid_product_basic_overview_field_output_alter($key, array &$output) {
  if ($key == 'product_overview') {
    $output = overview_field_load_view('product_overview', 'product_overview_block');
  }
  if ($key == 'product_overview_front') {
    $output = overview_field_load_view('product_overview', 'product_overview_front');
  }
  if ($key == 'block_winners_2019') {
    $output = overview_field_load_view('product_overview', 'block_winners_2019');
  }
  if ($key == 'block_winners_2020') {
    $output = overview_field_load_view('product_overview', 'block_winners_2020');
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function dropsolid_product_basic_migration_plugins_alter(&$definitions) {
  $path = drupal_get_path('module', 'dropsolid_product_basic');
  $definitions['migration_config_deriver:dropsolid_product_overview']['source']['path'] = $path . $definitions['migration_config_deriver:dropsolid_product_overview']['source']['path'];
  $definitions['migration_config_deriver:dropsolid_product_overview_header']['source']['path'] = $path . $definitions['migration_config_deriver:dropsolid_product_overview_header']['source']['path'];
  $definitions['migration_config_deriver:dropsolid_product_overview_p']['source']['path'] = $path . $definitions['migration_config_deriver:dropsolid_product_overview_p']['source']['path'];
}
