# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the PHP documentation
# (https://docs.platform.sh/languages/php.html#supported-versions)
# to find the supported versions for the 'php' type.
type: 'php:7.2'

# The following block defines a single writable directory, 'web/uploads'
# The 'source' specifies where the writable mount is. The 'local' source
# indicates that the mount point will point to a local directory on the
# application container. The 'source_path' specifies the subdirectory
# from within the source that the mount should point at.
mounts:
  # The default Drupal files directory.
  '/docroot/sites/default/files':
    source: local
    source_path: 'files'
  # Drupal gets its own dedicated tmp directory. The settings.platformsh.php
  # file will automatically configure Drupal to use this directory.
  '/tmp':
    source: local
    source_path: 'tmp'
  # Private file uploads are stored outside the web root. The settings.platformsh.php
  # file will automatically configure Drupal to use this directory.
  '/private':
    source: local
    source_path: 'private'
  # Drush needs a scratch space for its own caches.
  '/.drush':
    source: local
    source_path: 'drush'
  # Drush will try to save backups to this directory, so it must be
  # writeable even though you will almost never need to use it.
  '/drush-backups':
    source: local
    source_path: 'drush-backups'
  # Drupal Console will try to save backups to this directory, so it must be
  # writeable even though you will almost never need to use it.
  '/.console':
    source: local
    source_path: 'console'
  # Older DropSolid setup
  'docroot/uploads':
    source: local
    source_path: uploads

# The size of the persistent disk of the application (in MB).
disk: 2048

# Configuration of the build of this application.
build:
  flavor: none # no build steps, DropSolid code fully committed to repo as built

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form '<service name>:<endpoint name>'.
relationships:
    database: 'db:mysql'
    redis: 'cache:redis'
    solr: 'search:solr'

hooks:
    build: |
      set -e
    deploy: |
      set -e
      php ./drush/platformsh_generate_drush_yml.php
      # if drupal is installed, will call the following drush commands:
      #   - `cache-rebuild`
      #   - `updatedb`
      #   - and if config files are present, `config-import`
      cd docroot
      bash drush/platformsh_deploy_drupal.sh

web:
  locations:
    '/':
      root: "docroot"
      passthru: "/index.php"

      # Deny access to all static files, except those specifically allowed below.
      allow: false

      # Rules for specific URI patterns.
      rules:
        # Allow access to common static files.
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          allow: true
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true

        # Deny direct access to configuration files.
        '^/sites/sites\.php$':
          scripts: false
        '^/sites/[^/]+/settings.*?\.php$':
          scripts: false

    # The files directory has its own special configuration rules.
    '/sites/default/files':
      # Allow access to all files in the public files directory.
      allow: true
      expires: 5m
      passthru: '/index.php'
      root: 'docroot/sites/default/files'

      # Do not execute PHP scripts from the writeable mount.
      scripts: false

      rules:
        # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
        '^/sites/default/files/(css|js)':
          expires: 2w

crons:
  # Run Drupal's cron tasks every 15 minutes.
  drupal:
    spec: '*/15 * * * *'
    commands:
      start: 'cd web ; drush core-cron'
