<?php

/**
 * @file
 * Contains dropsolid_cookie_policy.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\Core\Cache\Cache;

/**
 * Implements hook_help().
 */
function dropsolid_cookie_policy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dropsolid_cookie_policy module.
    case 'help.page.dropsolid_cookie_policy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains functionality to include a cookie policy popup on every page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function dropsolid_cookie_policy_page_attachments(array &$attachments) {
  $cookiePolicyConfig = \Drupal::config('dropsolid_cookie_policy.cookiepolicyconfig');
  // Set cache tags (if config changes, the settings change).
  $cache_tags = isset($attachments['#cache']['tags']) ? $attachments['#cache']['tags'] : [];
  $attachments['#cache']['tags'] = Cache::mergeTags($cache_tags, $cookiePolicyConfig->getCacheTags());

  // Add cache context theme.
  $cache_context = isset($attachments['#cache']['contexts']) ? $attachments['#cache']['contexts'] : [];
  $attachments['#cache']['contexts'] = Cache::mergeContexts($cache_context, ['theme']);

  $current_theme = \Drupal::service('theme.manager')->getActiveTheme();
  $system_theme = \Drupal::config('system.theme');

  if ($system_theme->get('admin') !== $current_theme->getName()) {

    $nid = $cookiePolicyConfig->get('more_info_page');
    if (empty($nid)) {
      // Early return if no linked page is available.
      return;
    }

    // If nid is set, we also need to take it into account for cache tags
    // (for the url alias).
    $cache_tags = isset($attachments['#cache']['tags']) ? $attachments['#cache']['tags'] : [];
    $attachments['#cache']['tags'] = Cache::mergeTags($cache_tags, ['node:' . $nid]);

    $company_name = !empty($cookiePolicyConfig->get('company_name')) ? $cookiePolicyConfig->get('company_name') : \Drupal::config('system.site')
      ->get('name');

    $more_info_link = Link::fromTextAndUrl(t('More info.'), Url::fromRoute('entity.node.canonical', ['node' => $nid], [
      'absolute' => TRUE,
      'attributes' => [
        'target' => '_blank',
      ],
    ]))
      ->toString();

    $build = [
      '#theme' => 'dropsolid_cookie_policy_popup',
      '#template_first_line' => t('@company_name uses cookies to improve your online experience.', ['@company_name' => $company_name]),
      '#template_second_line' => t('By clicking on "I understand", you accept the use of cookies. @link', ['@link' => $more_info_link]),
      '#dismiss_text' => t('I understand'),
    ];

    /** @var \Twig_Environment $twig_service */
    $twig_service = \Drupal::service('twig');
    $was_debugging = FALSE;
    if ($twig_service->isDebug()) {
      $was_debugging = TRUE;
      $twig_service->disableDebug();
    }

    $renderedTemplate = \Drupal::service('renderer')
      ->renderRoot($build)
      ->__toString();

    if ($was_debugging) {
      $twig_service->enableDebug();
    }

    $attachments['#attached']['library'][] = 'dropsolid_cookie_policy/CookiePolicyPopup';
    $attachments['#attached']['drupalSettings']['dropsolid_cookie_policy']['template'] = $renderedTemplate;
  }
}

/**
 * Implements hook_theme().
 */
function dropsolid_cookie_policy_theme($existing, $type, $theme, $path) {
  return [
    'dropsolid_cookie_policy_popup' => [
      'variables' => [
        'template_first_line' => NULL,
        'template_second_line' => NULL,
        'dismiss_text' => NULL,
      ],
      'template' => 'cookie-policy-popup',
    ],
  ];
}
