<?php

/**
 * @file
 * Main module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_access().
 */
function dropsolid_event_advanced_webform_access(EntityInterface $entity, $operation, AccountInterface $account) {
  // Restrict access to editing this webform.
  /** @var \Drupal\webform\WebformInterface $entity */
  if (!$account->hasPermission('administer webform') && $entity->id() === 'event_subscription' && ($operation === 'update' || $operation === 'delete')) {
    return AccessResult::forbidden('This webform is part of a premade feature and can not be edited or deleted.')
      ->addCacheContexts(['user.permissions']);
  }
}

/**
 * Implements hook_theme().
 */
function dropsolid_event_advanced_theme($existing, $type, $theme, $path) {
  return [
    'event_facets_result_item' => [
      'base hook' => 'facets_result_item',
      'variables' => [
        'facet' => NULL,
        'raw_value' => '',
        'value' => '',
        'show_count' => FALSE,
        'count' => NULL,
        'is_active' => FALSE,
      ],
    ],
  ];
}

/**
 * Implements hook_local_tasks_alter().
 */
function dropsolid_event_advanced_menu_local_tasks_alter(&$local_tasks) {
  if (isset($local_tasks['tabs'][0]['webform_view:webform_views:view.event_subscriptions.event_submission_page'])) {
    // Only show Submissions link on Event nodes.
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof NodeInterface && $node->bundle() !== 'event') {
      unset($local_tasks['tabs'][0]['webform_view:webform_views:view.event_subscriptions.event_submission_page']);
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function dropsolid_event_advanced_form_webform_submission_event_subscription_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $form['scroll_to'] = [
    // Fingers crossed nobody puts two of these on the same page. Can't use
    // Unique ID method cuz this alter gets called twice per request.
    '#markup' => '<div id="subscribe-now" class="scroll-to-anchor"></div>',
    '#weight' => -9999,
  ];

}
