<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_themes_installed().
 *
 * Disable some blocks when one of our themes gets installed and this module
 * is already active at the time.
 */
function dropsolid_news_core_themes_installed($theme_list) {
  foreach ($theme_list as $theme) {
    if (in_array($theme, ['dropsolid_starter', 'dropsolid_flex'])) {
      Rocketship::hideBreadcrumbAndTitleBlockOnContentType($theme, 'news');
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure we go after block_themes_installed.
 */
function dropsolid_news_core_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'themes_installed') {
    $group = $implementations['dropsolid_news_core'];
    unset($implementations['dropsolid_news_core']);
    $implementations['dropsolid_news_core'] = $group;
  }
}

/**
 * Adds an option to the overview field.
 *
 * @param array $options
 *   Contains all the options for the overview field.
 */
function dropsolid_news_overview_field_options_alter(array &$options) {
  $options['news_overview'] = t('Show a list of news articles on your website');
  $options['news_overview_front'] = t('Show the last three promoted news articles on the front page');
}

/**
 * Defines what should be returned in the overview.
 *
 * @param string $key
 *   The key defined in hook_overview_options_alter().
 * @param array $output
 *   A renderable array of data, that needs to be displayed in the field.
 */
function dropsolid_news_overview_field_output_alter($key, array &$output) {
  if ($key == 'news_overview') {
    $output = overview_field_load_view('news_overview', 'news_overview_block');
  }
  if ($key == 'news_overview_front') {
    $output = overview_field_load_view('news_overview', 'news_overview_front');
  }
}

/**
 * Implements hook_theme().
 */
function dropsolid_news_theme($existing, $type, $theme, $path) {
  return [
    'news_facets_result_item' => [
      'base hook' => 'facets_result_item',
      'variables' => [
        'facet' => NULL,
        'raw_value' => '',
        'value' => '',
        'show_count' => FALSE,
        'count' => NULL,
        'is_active' => FALSE,
      ],
    ],
  ];
}

/**
 * Implements hook_theming_page_attachments().
 */
function dropsolid_news_core_page_attachments(array &$attachments) {

  // ** Load default library for styling if needed.
  // First get active theme name.
  $default_active_theme_name = \Drupal::service('theme.manager')
    ->getActiveTheme()->getName();

  // Get active theme libraries.
  $active_theme_library = \Drupal::service('library.discovery')
    ->getLibraryByName($default_active_theme_name, 'feature_news');

  // Get our default styling library.
  $module_library = \Drupal::service('library.discovery')
    ->getLibraryByName('dropsolid_news_core', 'structural');

  // If a 'structural css' library exists.
  if (isset($module_library)) {

    $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();

    // Check if active theme is NOT flex or starter
    // OR has no library called $active_theme_name/feature_blog
    // AND not in admin
    // load the module's structural css library.
    if (!$is_admin and
      (($default_active_theme_name !== 'dropsolid_flex' and $default_active_theme_name !== 'dropsolid_starter') or !isset($active_theme_library))
    ) {
      $attachments['#attached']['library'][] = 'dropsolid_news_core/structural';
    }
  }
}
