<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_themes_installed().
 */
function dropsolid_blocks_themes_installed($theme_list) {
  foreach ($theme_list as $theme) {
    if (in_array($theme, ['dropsolid_starter', 'dropsolid_flex'])) {
      dropsolid_blocks_place_default_blocks($theme);
    }
  }
}

/**
 * Place our blocks in the footer region of the provided theme.
 *
 * @param string $theme
 *   Theme name.
 */
function dropsolid_blocks_place_default_blocks($theme) {
  \Rocketship::placeBlock('powered_by_dropsolid', [
    'region' => 'footer',
    'theme' => $theme,
    'label' => 'Powered by platform.sh',
    'label_display' => 0,
  ]);

  \Rocketship::placeBlock('dropsolid_copyright_block', [
    'region' => 'footer',
    'theme' => $theme,
    'label' => 'Copyright',
    'terms_of_use' => NULL,
    'privacy_policy' => NULL,
    'company' => \Drupal::config('system.site')->get('name'),
    'label_display' => 0,
  ]);
}

/**
 * Implements hook_modules_implements_alter().
 *
 * Make sure we go after block_themes_installed.
 */
function dropsolid_blocks_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'themes_installed') {
    $group = $implementations['dropsolid_blocks'];
    unset($implementations['dropsolid_blocks']);
    $implementations['dropsolid_blocks'] = $group;
  }
}
