<?php

/**
 * @file
 * Main module file.
 */

/**
 * Adds an option to the overview field.
 *
 * @param array $options
 *   Contains all the options for the overview field.
 */
function dropsolid_nominee_overview_field_options_alter(array &$options) {
  $options['nominee_overview'] = t('Show a list of nominees on your website');
  $options['nominee_overview_front'] = t('Show the last four promoted nominees');
}

/**
 * Defines what should be returned in the overview.
 *
 * @param string $key
 *   The key defined in hook_overview_options_alter().
 * @param array $output
 *   A renderable array of data, that needs to be displayed in the field.
 */
function dropsolid_nominee_overview_field_output_alter($key, array &$output) {
  if ($key == 'nominee_overview') {
    $output = overview_field_load_view('nominee_overview', 'nominee_overview');
  }
  if ($key == 'nominee_overview_front') {
    $output = overview_field_load_view('nominee_overview_front', 'nominee_overview_front');
  }
}


