<?php

/**
 * @file
 * The main module file.
 */

use Drupal\Core\Cache\Cache;

/**
 * Adds an option to the overview field.
 *
 * @param array $options
 *   Contains all the options for the overview field.
 */
function dropsolid_blog_basic_overview_field_options_alter(array &$options) {
  $options['blog_overview'] = t('Show a list of blog articles on your website');
  $options['blog_overview_front'] = t('Show a limited list of promoted blog articles for your front page');
}

/**
 * Defines what should be returned in the overview.
 *
 * @param string $key
 *   The key defined in hook_overview_options_alter().
 * @param array $output
 *   A renderable array of data, that needs to be displayed in the field.
 */
function dropsolid_blog_basic_overview_field_output_alter($key, array &$output) {
  if ($key == 'blog_overview') {
    $output = overview_field_load_view('blog_overview', 'blog_overview_block');
  }
  if ($key == 'blog_overview_front') {
    $output = overview_field_load_view('blog_overview', 'blog_overview_front');
    // Cache this one, speed up homepage a bit for webadmin.
    $output['#cache']['max-age'] = Cache::PERMANENT;
    $output['#cache']['tags'][] = 'node_list';
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function dropsolid_blog_basic_migration_plugins_alter(&$definitions) {
  $path = drupal_get_path('module', 'dropsolid_blog_basic');
  $definitions['migration_config_deriver:dropsolid_blog_overview']['source']['path'] = $path . $definitions['migration_config_deriver:dropsolid_blog_overview']['source']['path'];
  $definitions['migration_config_deriver:dropsolid_blog_overview_header']['source']['path'] = $path . $definitions['migration_config_deriver:dropsolid_blog_overview_header']['source']['path'];
  $definitions['migration_config_deriver:dropsolid_blog_overview_p']['source']['path'] = $path . $definitions['migration_config_deriver:dropsolid_blog_overview_p']['source']['path'];
}
