#!/bin/sh

branch_name="$(git symbolic-ref HEAD 2>/dev/null)" ||
branch_name="unnamed branch"     # detached HEAD
branch_name=${branch_name##refs/heads/}

current_message=$(cat $1)
# Check that the branch name isn't already present
if ! [[ "$current_message" =~ ^\[\(.+\)\].*$ ]] ; then
    echo "[($branch_name)] $current_message" > .git/tmp-msg
    mv .git/tmp-msg $1
fi

exit 0