#!/bin/sh

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000


# make sure it starts with [(something)]
while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
		:
	else
		if [ "$remote_sha" = $z40 ]
		then
			# New branch, examine all commits
			range="$local_sha"
		else
			# Update to existing branch, examine new commits
			range="$remote_sha..$local_sha"
			echo $range
		fi

		# Check for branch name in commit message
		for commit in $(git rev-list $range)
        do
            MSG=$(git log -n 1 --pretty=format:%B $commit)
            if ! [[ "$MSG" =~ ^\[\(.+\)\].*$ ]] ; then
                echo >&2 "Did not find branch name in $MSG commit message, aborting git push"
                echo >&2 "Please ensure each commit has '[(branch_name)]' at the very start of the commit message"
                exit 1
            fi
        done
	fi
done

exit 0
