<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_themes_installed().
 *
 * Disable some blocks when one of our themes gets installed and this module
 * is already active at the time.
 */
function dropsolid_job_core_themes_installed($theme_list) {
  foreach ($theme_list as $theme) {
    if (in_array($theme, ['dropsolid_starter', 'dropsolid_flex'])) {
      Rocketship::hideBreadcrumbAndTitleBlockOnContentType($theme, 'job');
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure we go after block_themes_installed.
 */
function dropsolid_job_core_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'themes_installed') {
    $group = $implementations['dropsolid_job_core'];
    unset($implementations['dropsolid_job_core']);
    $implementations['dropsolid_job_core'] = $group;
  }
}

/**
 * Implements hook_theming_page_attachments().
 */
function dropsolid_job_core_page_attachments(array &$attachments) {

  // ** Load default library for styling if needed.
  // First get active theme name.
  $default_active_theme_name = \Drupal::service('theme.manager')
    ->getActiveTheme()->getName();

  // Get active theme libraries.
  $active_theme_library = \Drupal::service('library.discovery')
    ->getLibraryByName($default_active_theme_name, 'feature_job');

  // Get our default styling library.
  $module_library = \Drupal::service('library.discovery')
    ->getLibraryByName('dropsolid_job_core', 'structural');

  // If a 'structural css' library exists.
  if (isset($module_library)) {

    $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();

    // Check if active theme is NOT flex or starter
    // OR has no library called $active_theme_name/feature_blog
    // AND not in admin
    // load the module's structural css library.
    if (!$is_admin and
      (($default_active_theme_name !== 'dropsolid_flex' and $default_active_theme_name !== 'dropsolid_starter') or !isset($active_theme_library))
    ) {
      $attachments['#attached']['library'][] = 'dropsolid_job_core/structural';
    }
  }
}
