<?php

/**
 * @file
 * Main module file.
 */

/**
 * Adds an option to the overview field.
 *
 * @param array $options
 *   Contains all the options for the overview field.
 */
function dropsolid_event_basic_overview_field_options_alter(array &$options) {
  $options['event_overview'] = t('Show a list of upcoming events on your website');
  $options['event_overview_front'] = t('Show the next three upcoming promoted events');
  $options['event_archive_block'] = t('Show a list of past events on your website');
}

/**
 * Defines what should be returned in the overview.
 *
 * @param string $key
 *   The key defined in hook_overview_options_alter().
 * @param array $output
 *   A renderable array of data, that needs to be displayed in the field.
 */
function dropsolid_event_basic_overview_field_output_alter($key, array &$output) {
  // Search API views have Max-Age 0 by default.
  if ($key == 'event_overview') {
    $output = overview_field_load_view('event_overview', 'event_overview_block');
  }
  if ($key == 'event_overview_front') {
    // For the front page, we'd like some caching after all. It's already
    // got a lot of different stuff to load, and there's no facets to break
    // or anything fancy. A simple view mode, with a max-age to midnight
    // and node_list.
    $output = overview_field_load_view('event_overview', 'event_overview_front');
    $output['#cache']['max-age'] = strtotime('tomorrow') - time();
    $output['#cache']['tags'][] = 'node_list';
    $output['#cache']['contexts'][] = 'timezone';
  }
  if ($key == 'event_archive_block') {
    $output = overview_field_load_view('event_overview', 'event_archive_block');
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function dropsolid_event_basic_migration_plugins_alter(&$definitions) {
  $path = drupal_get_path('module', 'dropsolid_event_basic');
  $definitions['migration_config_deriver:dropsolid_event_overview']['source']['path'] = $path . $definitions['migration_config_deriver:dropsolid_event_overview']['source']['path'];
  $definitions['migration_config_deriver:dropsolid_event_overview_header']['source']['path'] = $path . $definitions['migration_config_deriver:dropsolid_event_overview_header']['source']['path'];
  $definitions['migration_config_deriver:dropsolid_event_overview_p']['source']['path'] = $path . $definitions['migration_config_deriver:dropsolid_event_overview_p']['source']['path'];
}
